### ISSUE TITLE
usage examples?

### ISSUE THREAD

**Issue by akrentsel** [piotrjurkiewicz/topohub#1]
Hi, could you please provide some simple usage examples for loading topologies with your library in python?

For example, I run this code:

```
import topohub.generate as thg
import networkx as nx

g = th.SNDLibGenerator.generate_topo('abilene')
print(g)
```

I get the following output: `{'directed': False, 'multigraph': False, 'graph': {'name': 'abilene', 'demands': {}}, 'nodes': [], 'links': []}`

I looked through your tests and didn't see examples.

**Comment by piotrjurkiewicz** [comment]
Hi!

The `SNDlibGenerator.generate_topo()` method downloads original topology definitions from SNDlib website and generates NetworkX node-link JSON graphs from them. It stopped to work because SNDlib changed their website address recently.

However, there is no need to use it. Generated JSON files for all SNDlib and Topology Zoo topologies are already included in the pip package, in the Git repository and are available via https://topohub.org. I added the `topohub.get()` helper to make easier accessing them in Python:

```python
import networkx as nx
import topohub

# Obtain topology dicts from JSON files stored in the repository
topo = topohub.get('gabriel/25/0')
topo = topohub.get('topozoo/Abilene')
topo = topohub.get('sndlib/polska')

# Create NetworkX graph from node-link dict
g = nx.node_link_graph(topo)

# Access graph parameters
print(g.graph['name'])
print(g.graph['demands'])
print(g.graph['stats']['avg_degree'])

# Obtain link length or ECMP routing utilization
print(g.edges['Bydgoszcz', 'Warsaw']['dist'])
print(g.edges['Bydgoszcz', 'Warsaw']['ecmp_fwd']['uni'])
```
BTW, the Topology Zoo website is apparently completely down. Fortunately, all the topologies are preserved in https://github.com/piotrjurkiewicz/topohub/tree/master/data/topozoo
